image: rocker/verse:latest

stages:
  - check
  - tests

before_script:
  - R -e 'devtools::install_deps(dependencies = TRUE)'

full_check:
  stage: check
  script:
    - R CMD build .
    - R CMD check --as-cran likelyprofiler_*.tar.gz
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

light_check:
  stage: tests
  script:
    - Rscript -e 'devtools::test()'
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'