image: rocker/tidyverse

before_script:
  - apt-get update && apt-get install -y \
      texlive \
      texlive-latex-base \
      texlive-fonts-recommended \
      texlive-latex-recommended \
      texlive-latex-extra \
      texlive-fonts-extra \
      tidy \
      libv8-dev \
      qpdf
  - R -e 'install.packages(c("V8"), repos = "https://cloud.r-project.org")'
  - R -e 'devtools::install_deps(dependencies = TRUE)'


check:
  script:
    - R CMD build .
    - R CMD check --as-cran likelyprofiler_*.tar.gz

